# Generated by Django 2.2.4 on 2020-12-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_app', '0002_auto_20201224_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
