# Generated by Django 2.2.4 on 2020-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_app', '0003_auto_20201224_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
