# Generated by Django 2.2.4 on 2020-12-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_app', '0005_auto_20201225_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
