# Generated by Django 2.2.4 on 2020-12-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_app', '0007_auto_20201225_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
